services:
  caddy:
    image: caddy:latest
    container_name: luoxu_caddy
    restart: always
    ports:
      - "15100:80"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - luoxu
      - web

  luoxu:
    image: ghcr.io/seele0oo/luoxu/luoxu:latest
    container_name: luoxu
    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@db:5432/luoxu_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9008:9008"
    volumes:
      - luoxu_data:/app
      - ./config/config.toml:/app/config.toml
      - ./luoxubot.session:/app/luoxubot.session
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9008/luoxu"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  db:
    image: ghcr.io/seele0oo/luoxu/luoxu-postgres-db:latest
    container_name: luoxu_db
    environment:
      POSTGRES_DB: luoxu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    image: ghcr.io/seele0oo/luoxu-web/luoxu:latest
    container_name: luoxu_web
    environment:
      VITE_LUOXU_URL: http://127.0.0.1:15100/luoxu
    # depends_on:
    #   luoxu:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
  luoxu_data:

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.100.0/24
